spring.application.name=hackhub
spring.datasource.url=jdbc:h2:file:./hackhub
spring.jpa.hibernate.ddl-auto=update

#attivare per debug sql
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false